# Homework

Task
* Find the hyperparameters that yield get the best predictions on the test dataset

Team
* Yufei Chu
* Kavish Vijay Daftari

Imoprting the libraries

In [1]:
import numpy as np
from urllib import request
import gzip
import pickle

Code to define two functions, download_mnist() and save_mnist(), that can be used to download and save the MNIST dataset.

In [2]:
filename = [
    ["training_images","train-images-idx3-ubyte.gz"],
    ["test_images","t10k-images-idx3-ubyte.gz"],
    ["training_labels","train-labels-idx1-ubyte.gz"],
    ["test_labels","t10k-labels-idx1-ubyte.gz"]
]

def download_mnist():
    base_url = "http://yann.lecun.com/exdb/mnist/"
    for name in filename:
        print("Downloading "+name[1]+"...")
        request.urlretrieve(base_url+name[1], name[1])
    print("Download complete.")

def save_mnist():
    mnist = {}
    for name in filename[:2]:
        with gzip.open(name[1], 'rb') as f:
            mnist[name[0]] = np.frombuffer(f.read(), np.uint8, offset=16).reshape(-1,28*28)
    for name in filename[-2:]:
        with gzip.open(name[1], 'rb') as f:
            mnist[name[0]] = np.frombuffer(f.read(), np.uint8, offset=8)
    with open("mnist.pkl", 'wb') as f:
        pickle.dump(mnist,f)
    print("Save complete.")

In [3]:
download_mnist()
save_mnist()

Download complete.
Save complete.


In [4]:
def load():
    with open(r"mnist.pkl",'rb') as f:
        mnist = pickle.load(f)
    return mnist["training_images"], mnist["training_labels"], mnist["test_images"], mnist["test_labels"]


Loading MINST dataset and storing the training and test images and labels into separate numpy arrays for further processing.

In [5]:
X_train, y_train, X_test, y_test = load()

In [6]:
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((60000, 784), (60000,), (10000, 784), (10000,))

In [7]:
X_train.size

47040000

Check if there are any *non-zero* elements in our matrices, use `np.any()`, which returns True if it finds at least one non-zero element:

In [8]:
np.any(X_train), np.any(X_test)

(True, True)

The sparsity of our dataset:

In [9]:
np.count_nonzero(X_train, axis=None) / X_train.size, np.count_nonzero(X_test, axis=None) / X_test.size

(0.19120229591836735, 0.1927575255102041)

In [10]:
np.any(y_train), np.any(y_test)

(True, True)

In [11]:
y_train

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

Prepare data so that it is *normalized* and *batched*:

In [12]:
def norm(X, x_min, x_max):
    nom = (X - X.min(axis=0)) * (x_max-x_min)
    denom = X.max(axis=0) - X.min(axis=0)
    denom[denom==0] = 1
    return x_min + nom/denom 

In [13]:
def prep_data(X, y):

    X_ = []
    y_ = []

    itr = int(len(y) / batch_size) + 1
    for j in range(1, itr):
        rng = j * batch_size
        X_.append(X[rng - batch_size : rng, :])
        y_.append(y[rng - batch_size : rng])

    X, y = np.array(X_), np.array(y_)
    X = norm(X, 0, 1)

    return X, y

## Tuning the hyperpatameter learning rates to 0.01

Our hyperparameters: `eta` and `alpha` are the multiplicative and additive **learning rates**, used to put the brakes on *giant* weight updates (baby steps!). `n_iter` is the number of training epochs, and `batch_size` is the size of our minibatch:

In [18]:
eta=0.01
alpha=0.01
n_iter=100
batch_size=50

In [19]:
eta, alpha, n_iter, batch_size

(0.01, 0.01, 100, 50)

Let's prepare our data:

In [20]:
X_train, y_train = prep_data(X_train, y_train)

In [21]:
X_train.shape, y_train.shape

((1200, 50, 784), (1200, 50))

In [22]:
1200 * 50

60000

In [23]:
np.count_nonzero(X_train, axis=None) / X_train.size

0.19120229591836735

One-hot encode our labels so that instead of many categories denoted by integers one through 10, we only have two categories: `0` and `1`, albeit in more dimensions.

In [24]:
def one_hot_enc(y, num_labels=10):
    one_hot = np.zeros((num_labels, y.shape[0]), dtype=np.float32)

    for i, val in enumerate(y):
        one_hot[val,i] = 1.0

    return one_hot

In [25]:
def one_hot_enc_v2(y, num_labels=10):
    one_hot = np.zeros((y.shape[0], num_labels), dtype=np.float32)

    for i, val in enumerate(y):
        one_hot[i,val] = 1.0

    return one_hot

Initialize our weights:

In [26]:
def init_weights(n_input, n_hidden_1, n_hidden_2, n_output, batch_size):
    #w1 = np.random.randn(n_hidden_1, n_input + 1)
    #w2 = np.random.randn(n_hidden_2, n_hidden_1 + 1)
    #w3 = np.random.randn(n_output, n_hidden_2 + 1)
    
    w1 = np.random.randn(n_input, n_hidden_1)
    w2 = np.random.randn(n_hidden_1, n_hidden_2)
    w3 = np.random.randn(n_hidden_2, n_output)
    
    return w1, w2, w3

Binary cross-entropy loss:

In [27]:
def compute_loss(prediction, label):
    term_1 = -1*label * np.log(prediction)
    term_2 = (1 - label) * (np.log(1 - prediction))

    loss = np.sum(term_1 - term_2)
    return loss

Initialize the number of neurons per layer:

In [28]:
n_hidden_1, n_hidden_2, n_output = 100, 100, 10
n_input = len(X_train[0,0,:]) #returns the flattened image size (28*28 = 784)
n_input

784

Initialize the weight1, weight2, weight3

In [29]:
w1, w2, w3 = init_weights(n_input, n_hidden_1, n_hidden_2, n_output, batch_size)

Initialize Markovian weight history, losses and accuracy per epoch:

In [30]:
delta_w1_prev = np.zeros(w1.shape)
delta_w2_prev = np.zeros(w2.shape)
delta_w3_prev = np.zeros(w3.shape)

train_losses = []
train_acc = []

Here is the full code for the **feedforward pass** (we return input and all outputs):

In [31]:
def compute_forward_pass(inputs):   
    a1 = inputs

    # outputs of first hidden layer
    z2 = np.matmul(a1, w1)
    a2 = 1/(1 + np.exp(-z2))

    # outputs of second hidden layer
    z3 = np.matmul(a2, w2)
    a3 = 1/(1 + np.exp(-z3))

    # outputs of final layer
    z4 = np.matmul(a3, w3)
    a4 = 1/(1 + np.exp(-z4))
    
    return a1, z2, a2, z3, a3, z4, a4

In **backpropagation**, we evaluate the gradients of the loss with respect to the weights of each layer. 

The **gradient descent algorithm** consists in subtracting the respective gradient from each layer's weights (subject to an additive and multiplicative "*brake*" in order to take baby steps in that direction) so that we may reach the point where we minimize the difference between labels and predictions.

<br />
<center>
<img src =ipynb.images/duck-baby-steps.png width = 400 />
</center>

## 2 Hidden layers equations
Our equations for two hidden layers are ($\hat{y}$ is the output of the network while $y$ is the label, $z$ is the output of hidden layer 2, $r$ is the output of hidden layer 1, and $x$ is the input):

$$\frac{\partial \;\text{Loss}(y, \hat{y})}{\partial W^3} = 
2(y - \hat{y}) * \sigma'(W^3 z) \otimes z$$

$$\frac{\partial \;\text{Loss}(y, \hat{y})}{\partial W^2} = 
2(y - \hat{y}) * \sigma'(W^3 z)  \otimes W^3 *
\sigma'(W^2 r) \otimes r$$

$$\frac{\partial \;\text{Loss}(y, \hat{y})}{\partial W^1} =
2(y - \hat{y}) * \sigma'(W^3 z) \otimes W^3 
* \sigma'(W^2 r) \otimes W^2 * \sigma'(W^1 x) \otimes x$$

`a` for activation: `a1` is the input data, `a2` is the output of hidden layer 1, `a3` is the output of hidden layer 2, `a4` is the output of the final layer.

`z` for linear data: `z1` is the input data, `z2` is the linear output of hidden layer 1 *before its activation function*, `z3` is the linear output of hidden layer 2 *before its activation function*, `z4` is the linear output of the final layer *before its activation function*.

In analogy with our `ml_dense_pruned` notebook, $\hat{y}$ is the output of the network while $y$ is the label, $z$ is the output of hidden layer 2, $r$ is the output of hidden layer 1, and $x$ is the input. In code, $z = $ `self.layer2` is the output of hidden layer 2, and $r = $ `self.layer1` is the output of hidden layer 1. 

$\sigma'(W^3 z) = $ `sigmoid_derivative_3`.

$\sigma'(W^2 r) = $ `sigmoid_derivative_2`.

$\sigma'(W^1 z) = $ `sigmoid_derivative_1`.

Here's our activation function and its derivative:

In [32]:
def sigmoid(x):
    try:
        x = np.vectorize(round)(x)
        return 1.0/(1+ np.exp(-x))
    except:
        print(x)
        print(np.exp(-x))
        return 1.0/(1+ np.exp(-x))

In [33]:
def sigmoid_derivative(x):
    return sigmoid(x) * (1.0 - sigmoid(x))

Backpropagation pass:

In [34]:
def compute_backward_pass_fullmath(outputs, label, verbose=False):
    a1, z2, a2, z3, a3, z4, a4 = outputs

    #
    # LAST LAYER
    #
    
    # from ml-dense-pruned:
    # sigmoid_derivative_3 = sigmoid_derivative(np.dot(self.layer2, self.weights3)) # s'(W3 z) derivative of final layer output
    # d_weights3 = np.dot(self.layer2.T, 
    #                        (2*(self.y - self.output) * sigmoid_derivative_3))
    sigmoid_derivative_3 = sigmoid_derivative(np.dot(a3, w3)) # s'(W3 z) derivative of final layer output [50, 10]
    if verbose: print("sigmoid_derivative_3:", sigmoid_derivative_3.shape, "should be [50, 10]")
    d_weights3 = np.dot(a3.T, 
                           (2 * (label - a4) * sigmoid_derivative_3)) # [50, 100].T * [50, 10]
    if verbose: print("d_weights3:", d_weights3.shape, "should be [100, 10]")
    
    
    # 
    # 2ND HIDDEN LAYER
    #

    # from ml-dense-pruned:
    # sigmoid_derivative_2 = sigmoid_derivative(np.dot(self.layer1, self.weights2)) # s'(r W2) derivative of hidden layer 2 out
    # d_weights2 = np.dot(self.layer1.T,  
    #                        np.dot(2*(self.y - self.output) * sigmoid_derivative_3, self.weights3.T) * 
    #                        sigmoid_derivative_2)
    sigmoid_derivative_2 = sigmoid_derivative(np.dot(a2, w2)) # s'(r W2) derivative of hidden layer 2 out
    if verbose: print("sigmoid_derivative_2:", sigmoid_derivative_2.shape, "should be [50, 100]")
    d_weights2 = np.dot(a2.T,  
                        np.dot((2 * (label - a4) * sigmoid_derivative_3), w3.T) * 
                        sigmoid_derivative_2) # [50, 100].T * ([50, 10] * [100, 10].T)[50, 100] = [50, 100].T * [50, 100] 
                                                                                                # = [100, 100]
    if verbose: print("d_weights2:", d_weights2.shape, "should be [100, 100]")
    
    
    # 
    # 1ST HIDDEN LAYER
    #
    
    # from ml-dense-pruned:
    # sigmoid_derivative_1 = sigmoid_derivative(np.dot(self.input, self.weights1))  # s'(x W1) derivative of hidden layer 1 out
    # d_weights1 = np.dot(self.input.T,  
    #                        np.dot(
    #                            np.dot(2*(self.y - self.output) * sigmoid_derivative_3, self.weights3.T) *
    #                                sigmoid_derivative_2, self.weights2.T) *   
    #                        sigmoid_derivative_1)
    sigmoid_derivative_1 = sigmoid_derivative(np.dot(a1, w1))  # s'(x W1) derivative of hidden layer 1 out [50, 100]
    if verbose: print("sigmoid_derivative_1:", sigmoid_derivative_1.shape, "should be [50, 100]")
    d_weights1 = np.dot(a1.T,  
                           np.dot(
                               np.dot((2 * (label - a4) * sigmoid_derivative_3), w3.T) *
                                   sigmoid_derivative_2, w2.T) *   
                           sigmoid_derivative_1) # [50, 784].T * (([50, 100] * [100, 100].T) . [50, 100]) * [100, 100].T)
                                                # = [50, 784].T * [50, 100] * [100, 100].T
                                                # = [50, 784].T * [50, 100].T
                                                # = [784, 100]
    if verbose: print("d_weights1:", d_weights1.shape, "should be [784, 100]")

    return d_weights1, d_weights2, d_weights3

Predict from the output of 10 neurons, representing the digit predicted in a one-hot encoded fashion:

In [35]:
def predict(a4):
    prediction = np.argmax(a4, axis=1)
    return prediction

The training dataset:

In [36]:
X_train.shape, y_train.shape

((1200, 50, 784), (1200, 50))

In [37]:
X_train[:, 0, ]

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [38]:
np.any(X_train)

True

In [39]:
y_train

array([[5, 0, 4, ..., 5, 9, 3],
       [3, 0, 7, ..., 8, 3, 1],
       [5, 7, 1, ..., 6, 7, 3],
       ...,
       [5, 7, 4, ..., 2, 0, 9],
       [4, 0, 1, ..., 5, 9, 8],
       [8, 4, 0, ..., 5, 6, 8]], dtype=uint8)

This is how to iterate over the training dataset:

Let's debug *one batch* of one epoch:

## Set the hyperparameter learning rate = 0.01, epoch = 100:

In [40]:
eta=0.01
alpha=0.01
batch_size=50
n_iter = 100

In [ ]:
from tqdm import tqdm
#epoch loop
for i in tqdm(range(n_iter)):
    # batch loop
    for (input, label) in zip(X_train, y_train):
        one_hot_label = one_hot_enc_v2(label, num_labels=10)

        a1, z2, a2, z3, a3, z4, a4 = compute_forward_pass(input)
        loss = compute_loss(a4, one_hot_label)
        grad1, grad2, grad3 = compute_backward_pass_fullmath([a1, z2, a2, z3, a3, z4, a4], one_hot_label)

        # multiplicative learning factor
        delta_w1, delta_w2, delta_w3 = eta * grad1, eta * grad2, eta * grad3

        # additive learning factor
        w1 = w1 + delta_w1 + delta_w1_prev * alpha
        w2 = w2 + delta_w2 + delta_w2_prev * alpha
        w3 = w3 + delta_w3 + delta_w3_prev * alpha

        delta_w1_prev, delta_w2_prev, delta_w3_prev = delta_w1, delta_w2, delta_w3

        train_losses.append(loss)
        predictions = predict(a4)

        wrong = np.where(predictions != label, np.matrix([1.]), np.matrix([0.]))
        accuracy = 1 - (np.sum(wrong) / batch_size)
        train_acc.append(accuracy)

    # epoch loss and accuracy (mean of al batches)
    print('epoch ', i, 'loss %.2f' % np.mean(np.matrix(train_losses)).item(), 
          'training accuracy %.2f' % np.mean(np.matrix(train_acc)).item())

  1%|          | 1/100 [00:26<44:25, 26.92s/it]

epoch  0 loss 207.64 training accuracy 0.49


  2%|▏         | 2/100 [00:43<34:01, 20.83s/it]

epoch  1 loss 159.16 training accuracy 0.62


  3%|▎         | 3/100 [00:59<30:21, 18.78s/it]

epoch  2 loss 139.03 training accuracy 0.67


  4%|▍         | 4/100 [01:16<28:24, 17.75s/it]

epoch  3 loss 127.70 training accuracy 0.71


  5%|▌         | 5/100 [01:34<28:15, 17.85s/it]

epoch  4 loss 120.33 training accuracy 0.73


  6%|▌         | 6/100 [01:51<27:39, 17.66s/it]

epoch  5 loss 115.04 training accuracy 0.75


  7%|▋         | 7/100 [02:07<26:44, 17.25s/it]

epoch  6 loss 110.98 training accuracy 0.76


  8%|▊         | 8/100 [02:24<25:58, 16.95s/it]

epoch  7 loss 107.69 training accuracy 0.77


  9%|▉         | 9/100 [02:40<25:28, 16.79s/it]

epoch  8 loss 104.94 training accuracy 0.78


 10%|█         | 10/100 [02:56<24:58, 16.65s/it]

epoch  9 loss 102.54 training accuracy 0.78


 11%|█         | 11/100 [03:13<24:32, 16.55s/it]

epoch  10 loss 100.32 training accuracy 0.79


 12%|█▏        | 12/100 [03:28<23:46, 16.21s/it]

epoch  11 loss 98.10 training accuracy 0.79


 13%|█▎        | 13/100 [03:44<23:12, 16.01s/it]

epoch  12 loss 94.45 training accuracy 0.80


 14%|█▍        | 14/100 [04:00<23:19, 16.27s/it]

epoch  13 loss 89.35 training accuracy 0.81


 15%|█▌        | 15/100 [04:16<22:52, 16.15s/it]

epoch  14 loss 84.83 training accuracy 0.82


 16%|█▌        | 16/100 [04:32<22:16, 15.91s/it]

epoch  15 loss 80.82 training accuracy 0.83


 17%|█▋        | 17/100 [04:47<21:50, 15.79s/it]

epoch  16 loss 77.24 training accuracy 0.83


 18%|█▊        | 18/100 [05:04<21:50, 15.98s/it]

epoch  17 loss 74.02 training accuracy 0.84


 19%|█▉        | 19/100 [05:20<21:53, 16.22s/it]

epoch  18 loss 71.11 training accuracy 0.85


 20%|██        | 20/100 [05:36<21:13, 15.92s/it]

epoch  19 loss 68.46 training accuracy 0.85


 21%|██        | 21/100 [05:52<21:15, 16.14s/it]

epoch  20 loss 66.05 training accuracy 0.86


 22%|██▏       | 22/100 [06:08<20:57, 16.13s/it]

epoch  21 loss 63.84 training accuracy 0.86


 23%|██▎       | 23/100 [06:24<20:25, 15.92s/it]

epoch  22 loss 61.80 training accuracy 0.87


 24%|██▍       | 24/100 [06:39<19:55, 15.74s/it]

epoch  23 loss 59.92 training accuracy 0.87


 25%|██▌       | 25/100 [06:55<19:32, 15.64s/it]

epoch  24 loss 58.17 training accuracy 0.87


 26%|██▌       | 26/100 [07:10<19:18, 15.65s/it]

epoch  25 loss 56.55 training accuracy 0.88


 27%|██▋       | 27/100 [07:26<18:58, 15.60s/it]

epoch  26 loss 55.04 training accuracy 0.88


 28%|██▊       | 28/100 [07:41<18:38, 15.54s/it]

epoch  27 loss 53.62 training accuracy 0.88


 29%|██▉       | 29/100 [07:57<18:38, 15.76s/it]

epoch  28 loss 52.30 training accuracy 0.89


 30%|███       | 30/100 [08:14<18:35, 15.94s/it]

epoch  29 loss 51.05 training accuracy 0.89


 31%|███       | 31/100 [08:29<18:02, 15.69s/it]

epoch  30 loss 49.88 training accuracy 0.89


 32%|███▏      | 32/100 [08:44<17:36, 15.54s/it]

epoch  31 loss 48.77 training accuracy 0.89


 33%|███▎      | 33/100 [08:59<17:15, 15.45s/it]

epoch  32 loss 47.73 training accuracy 0.90


 34%|███▍      | 34/100 [09:15<16:56, 15.40s/it]

epoch  33 loss 46.74 training accuracy 0.90


 35%|███▌      | 35/100 [09:30<16:44, 15.45s/it]

epoch  34 loss 45.80 training accuracy 0.90


 36%|███▌      | 36/100 [09:45<16:24, 15.39s/it]

epoch  35 loss 44.91 training accuracy 0.90


 37%|███▋      | 37/100 [10:01<16:14, 15.47s/it]

epoch  36 loss 44.06 training accuracy 0.90


 38%|███▊      | 38/100 [10:18<16:23, 15.86s/it]

epoch  37 loss 43.26 training accuracy 0.91


 39%|███▉      | 39/100 [10:34<16:20, 16.07s/it]

epoch  38 loss 42.49 training accuracy 0.91


 40%|████      | 40/100 [10:50<15:52, 15.88s/it]

epoch  39 loss 41.75 training accuracy 0.91


 41%|████      | 41/100 [11:05<15:26, 15.71s/it]

epoch  40 loss 41.05 training accuracy 0.91


 42%|████▏     | 42/100 [11:20<15:03, 15.57s/it]

epoch  41 loss 40.38 training accuracy 0.91


 43%|████▎     | 43/100 [11:36<14:42, 15.49s/it]

epoch  42 loss 39.74 training accuracy 0.91


 44%|████▍     | 44/100 [11:51<14:22, 15.40s/it]

epoch  43 loss 39.12 training accuracy 0.91


 45%|████▌     | 45/100 [12:06<14:06, 15.39s/it]

epoch  44 loss 38.53 training accuracy 0.92


 46%|████▌     | 46/100 [12:21<13:49, 15.36s/it]

epoch  45 loss 37.96 training accuracy 0.92


 47%|████▋     | 47/100 [12:39<14:08, 16.01s/it]

epoch  46 loss 37.41 training accuracy 0.92


 48%|████▊     | 48/100 [12:55<13:58, 16.12s/it]

epoch  47 loss 36.89 training accuracy 0.92


 49%|████▉     | 49/100 [13:11<13:37, 16.03s/it]

epoch  48 loss 36.38 training accuracy 0.92


 50%|█████     | 50/100 [13:27<13:19, 15.99s/it]

epoch  49 loss 35.89 training accuracy 0.92


 51%|█████     | 51/100 [13:43<12:59, 15.91s/it]

epoch  50 loss 35.42 training accuracy 0.92


 52%|█████▏    | 52/100 [13:58<12:37, 15.79s/it]

epoch  51 loss 34.97 training accuracy 0.92


 53%|█████▎    | 53/100 [14:14<12:19, 15.73s/it]

epoch  52 loss 34.53 training accuracy 0.92


 54%|█████▍    | 54/100 [14:30<12:08, 15.84s/it]

epoch  53 loss 34.10 training accuracy 0.93


 55%|█████▌    | 55/100 [14:47<12:08, 16.18s/it]

epoch  54 loss 33.69 training accuracy 0.93


 56%|█████▌    | 56/100 [15:02<11:41, 15.94s/it]

epoch  55 loss 33.29 training accuracy 0.93


 57%|█████▋    | 57/100 [15:18<11:20, 15.83s/it]

epoch  56 loss 32.91 training accuracy 0.93


 58%|█████▊    | 58/100 [15:34<11:04, 15.83s/it]

epoch  57 loss 32.53 training accuracy 0.93


 59%|█████▉    | 59/100 [15:50<10:49, 15.84s/it]

epoch  58 loss 32.17 training accuracy 0.93


 60%|██████    | 60/100 [16:05<10:32, 15.80s/it]

epoch  59 loss 31.82 training accuracy 0.93


 61%|██████    | 61/100 [16:22<10:20, 15.92s/it]

epoch  60 loss 31.48 training accuracy 0.93


 62%|██████▏   | 62/100 [16:39<10:26, 16.49s/it]

epoch  61 loss 31.15 training accuracy 0.93


 63%|██████▎   | 63/100 [16:55<10:02, 16.28s/it]

epoch  62 loss 30.83 training accuracy 0.93


 64%|██████▍   | 64/100 [17:11<09:37, 16.05s/it]

epoch  63 loss 30.51 training accuracy 0.93


 65%|██████▌   | 65/100 [17:26<09:18, 15.95s/it]

epoch  64 loss 30.21 training accuracy 0.93


 66%|██████▌   | 66/100 [17:42<08:59, 15.85s/it]

epoch  65 loss 29.91 training accuracy 0.93


 67%|██████▋   | 67/100 [17:57<08:38, 15.71s/it]

epoch  66 loss 29.62 training accuracy 0.94


 68%|██████▊   | 68/100 [18:13<08:21, 15.67s/it]

epoch  67 loss 29.34 training accuracy 0.94


 69%|██████▉   | 69/100 [18:30<08:16, 16.00s/it]

epoch  68 loss 29.07 training accuracy 0.94


 70%|███████   | 70/100 [18:46<08:03, 16.10s/it]

epoch  69 loss 28.80 training accuracy 0.94


 71%|███████   | 71/100 [19:01<07:40, 15.89s/it]

epoch  70 loss 28.54 training accuracy 0.94


 72%|███████▏  | 72/100 [19:17<07:22, 15.81s/it]

epoch  71 loss 28.29 training accuracy 0.94


 73%|███████▎  | 73/100 [19:32<07:03, 15.68s/it]

epoch  72 loss 28.04 training accuracy 0.94


 74%|███████▍  | 74/100 [19:48<06:47, 15.67s/it]

epoch  73 loss 27.80 training accuracy 0.94


 75%|███████▌  | 75/100 [20:04<06:31, 15.67s/it]

epoch  74 loss 27.57 training accuracy 0.94


 76%|███████▌  | 76/100 [20:20<06:22, 15.95s/it]

epoch  75 loss 27.34 training accuracy 0.94


 77%|███████▋  | 77/100 [20:38<06:16, 16.35s/it]

epoch  76 loss 27.11 training accuracy 0.94


 78%|███████▊  | 78/100 [20:54<05:58, 16.30s/it]

epoch  77 loss 26.90 training accuracy 0.94


 79%|███████▉  | 79/100 [21:10<05:39, 16.18s/it]

epoch  78 loss 26.68 training accuracy 0.94


 80%|████████  | 80/100 [21:25<05:20, 16.04s/it]

epoch  79 loss 26.47 training accuracy 0.94


 81%|████████  | 81/100 [21:42<05:05, 16.07s/it]

epoch  80 loss 26.27 training accuracy 0.94


 82%|████████▏ | 82/100 [21:58<04:50, 16.13s/it]

epoch  81 loss 26.07 training accuracy 0.94


 83%|████████▎ | 83/100 [22:15<04:40, 16.49s/it]

epoch  82 loss 25.87 training accuracy 0.94


 84%|████████▍ | 84/100 [22:32<04:25, 16.61s/it]

epoch  83 loss 25.68 training accuracy 0.94


 85%|████████▌ | 85/100 [22:48<04:05, 16.34s/it]

epoch  84 loss 25.49 training accuracy 0.94


 86%|████████▌ | 86/100 [23:04<03:48, 16.29s/it]

epoch  85 loss 25.31 training accuracy 0.95


 87%|████████▋ | 87/100 [23:20<03:31, 16.27s/it]

epoch  86 loss 25.13 training accuracy 0.95


 88%|████████▊ | 88/100 [23:37<03:15, 16.32s/it]

epoch  87 loss 24.95 training accuracy 0.95


 89%|████████▉ | 89/100 [23:54<03:02, 16.57s/it]

epoch  88 loss 24.78 training accuracy 0.95


 90%|█████████ | 90/100 [24:12<02:49, 16.95s/it]

epoch  89 loss 24.61 training accuracy 0.95


 91%|█████████ | 91/100 [24:28<02:31, 16.81s/it]

epoch  90 loss 24.45 training accuracy 0.95


 92%|█████████▏| 92/100 [24:45<02:13, 16.70s/it]

epoch  91 loss 24.28 training accuracy 0.95


 93%|█████████▎| 93/100 [25:01<01:55, 16.54s/it]

epoch  92 loss 24.12 training accuracy 0.95


 94%|█████████▍| 94/100 [25:17<01:38, 16.46s/it]

epoch  93 loss 23.97 training accuracy 0.95


 95%|█████████▌| 95/100 [25:34<01:22, 16.52s/it]

epoch  94 loss 23.81 training accuracy 0.95


 96%|█████████▌| 96/100 [25:50<01:06, 16.60s/it]

epoch  95 loss 23.66 training accuracy 0.95


 97%|█████████▋| 97/100 [26:06<00:48, 16.33s/it]

epoch  96 loss 23.52 training accuracy 0.95


 98%|█████████▊| 98/100 [26:22<00:32, 16.23s/it]

epoch  97 loss 23.37 training accuracy 0.95


 99%|█████████▉| 99/100 [26:39<00:16, 16.41s/it]

epoch  98 loss 23.23 training accuracy 0.95


100%|██████████| 100/100 [26:55<00:00, 16.16s/it]

epoch  99 loss 23.09 training accuracy 0.95


The loss keeps *decreasing*, so that is encouraging. We need to run more epochs! We can also play with the learning rates!

Verify with the test set:

In [ ]:
y_test

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

In [53]:
y_test_one_hot = np.zeros((y_test.shape[0], 10), dtype=np.float32)

for i, val in enumerate(y_test):
    y_test_one_hot[i, val] = 1.0
    
print(y_test_one_hot)

[[0. 0. 0. ... 1. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [ ]:
X_test.shape, y_test.shape, y_test_one_hot.shape

((10000, 784), (10000,), (10000, 10))

To predict the test dataset, we run one feedforward pass with a batch of size 10,000!

In [ ]:
a1, z2, a2, z3, a3, z4, a4 = compute_forward_pass(X_test)
loss = compute_loss(a4, y_test_one_hot)
predictions = predict(a4)
predictions

<ipython-input-27-a5da05856836>:6: RuntimeWarning: overflow encountered in exp
  a2 = 1/(1 + np.exp(-z2))


array([7, 2, 1, ..., 4, 5, 6])

In [ ]:
labels = predict(y_test_one_hot)
labels

array([7, 2, 1, ..., 4, 5, 6])

In [ ]:
wrong = np.where(predictions != labels, np.matrix([1.]), np.matrix([0.]))
test_accuracy = 1 - (np.sum(wrong) / 10000)
test_accuracy

0.9453

## Set the hyperparameter learning rate = 0.001, epoch = 100:

In [14]:
eta=0.001
alpha=0.001
batch_size=50
n_iter = 100

### Reinitialize the parameter

Initialize the number of neurons per layer:

In [41]:
n_hidden_1, n_hidden_2, n_output = 100, 100, 10
n_input = len(X_train[0,0,:]) #returns the flattened image size (28*28 = 784)
n_input

784

Initialize the weight1, weight2, weight3

In [42]:
w1, w2, w3 = init_weights(n_input, n_hidden_1, n_hidden_2, n_output, batch_size)

Initialize Markovian weight history, losses and accuracy per epoch:

In [43]:
delta_w1_prev = np.zeros(w1.shape)
delta_w2_prev = np.zeros(w2.shape)
delta_w3_prev = np.zeros(w3.shape)

train_losses = []
train_acc = []

In [ ]:
from tqdm import tqdm
#epoch loop
for i in tqdm(range(n_iter)):
    # batch loop
    for (input, label) in zip(X_train, y_train):
        one_hot_label = one_hot_enc_v2(label, num_labels=10)

        a1, z2, a2, z3, a3, z4, a4 = compute_forward_pass(input)
        loss = compute_loss(a4, one_hot_label)
        grad1, grad2, grad3 = compute_backward_pass_fullmath([a1, z2, a2, z3, a3, z4, a4], one_hot_label)

        # multiplicative learning factor
        delta_w1, delta_w2, delta_w3 = eta * grad1, eta * grad2, eta * grad3

        # additive learning factor
        w1 = w1 + delta_w1 + delta_w1_prev * alpha
        w2 = w2 + delta_w2 + delta_w2_prev * alpha
        w3 = w3 + delta_w3 + delta_w3_prev * alpha

        delta_w1_prev, delta_w2_prev, delta_w3_prev = delta_w1, delta_w2, delta_w3

        train_losses.append(loss)
        predictions = predict(a4)

        wrong = np.where(predictions != label, np.matrix([1.]), np.matrix([0.]))
        accuracy = 1 - (np.sum(wrong) / batch_size)
        train_acc.append(accuracy)

    # epoch loss and accuracy (mean of al batches)
    print('epoch ', i, 'loss %.2f' % np.mean(np.matrix(train_losses)).item(), 
          'training accuracy %.2f' % np.mean(np.matrix(train_acc)).item())

In [ ]:
a1, z2, a2, z3, a3, z4, a4 = compute_forward_pass(X_test)
loss = compute_loss(a4, y_test_one_hot)
predictions = predict(a4)
predictions

<ipython-input-27-a5da05856836>:6: RuntimeWarning: overflow encountered in exp
  a2 = 1/(1 + np.exp(-z2))


array([7, 2, 1, ..., 9, 8, 6])

In [ ]:
labels = predict(y_test_one_hot)
labels

array([7, 2, 1, ..., 4, 5, 6])

In [ ]:
wrong = np.where(predictions != labels, np.matrix([1.]), np.matrix([0.]))
test_accuracy = 1 - (np.sum(wrong) / 10000)
test_accuracy

0.7429

## Set the hyperparameter learning rate = 0.01, epoch = 50:

In [45]:
eta=0.01
alpha=0.01
batch_size=50
n_iter = 50

### Reinitialize the parameter

Initialize the number of neurons per layer:

In [47]:
n_hidden_1, n_hidden_2, n_output = 100, 100, 10
n_input = len(X_train[0,0,:]) #returns the flattened image size (28*28 = 784)
n_input

784

Initialize the weight1, weight2, weight3

In [48]:
w1, w2, w3 = init_weights(n_input, n_hidden_1, n_hidden_2, n_output, batch_size)

Initialize Markovian weight history, losses and accuracy per epoch:

In [49]:
delta_w1_prev = np.zeros(w1.shape)
delta_w2_prev = np.zeros(w2.shape)
delta_w3_prev = np.zeros(w3.shape)

train_losses = []
train_acc = []

In [50]:
from tqdm import tqdm
#epoch loop
for i in tqdm(range(n_iter)):
    # batch loop
    for (input, label) in zip(X_train, y_train):
        one_hot_label = one_hot_enc_v2(label, num_labels=10)

        a1, z2, a2, z3, a3, z4, a4 = compute_forward_pass(input)
        loss = compute_loss(a4, one_hot_label)
        grad1, grad2, grad3 = compute_backward_pass_fullmath([a1, z2, a2, z3, a3, z4, a4], one_hot_label)

        # multiplicative learning factor
        delta_w1, delta_w2, delta_w3 = eta * grad1, eta * grad2, eta * grad3

        # additive learning factor
        w1 = w1 + delta_w1 + delta_w1_prev * alpha
        w2 = w2 + delta_w2 + delta_w2_prev * alpha
        w3 = w3 + delta_w3 + delta_w3_prev * alpha

        delta_w1_prev, delta_w2_prev, delta_w3_prev = delta_w1, delta_w2, delta_w3

        train_losses.append(loss)
        predictions = predict(a4)

        wrong = np.where(predictions != label, np.matrix([1.]), np.matrix([0.]))
        accuracy = 1 - (np.sum(wrong) / batch_size)
        train_acc.append(accuracy)

    # epoch loss and accuracy (mean of al batches)
    print('epoch ', i, 'loss %.2f' % np.mean(np.matrix(train_losses)).item(), 
          'training accuracy %.2f' % np.mean(np.matrix(train_acc)).item())

  2%|▏         | 1/50 [00:16<13:48, 16.92s/it]

epoch  0 loss 322.52 training accuracy 0.43


  4%|▍         | 2/50 [00:33<13:11, 16.49s/it]

epoch  1 loss 224.86 training accuracy 0.57


  6%|▌         | 3/50 [00:49<12:54, 16.49s/it]

epoch  2 loss 186.97 training accuracy 0.64


  8%|▊         | 4/50 [01:06<12:40, 16.54s/it]

epoch  3 loss 166.46 training accuracy 0.68


 10%|█         | 5/50 [01:22<12:25, 16.56s/it]

epoch  4 loss 153.47 training accuracy 0.71


 12%|█▏        | 6/50 [01:40<12:28, 17.01s/it]

epoch  5 loss 144.40 training accuracy 0.73


 14%|█▍        | 7/50 [01:58<12:27, 17.39s/it]

epoch  6 loss 137.63 training accuracy 0.74


 16%|█▌        | 8/50 [02:15<11:59, 17.14s/it]

epoch  7 loss 132.30 training accuracy 0.75


 18%|█▊        | 9/50 [02:31<11:32, 16.89s/it]

epoch  8 loss 127.99 training accuracy 0.76


 20%|██        | 10/50 [02:48<11:09, 16.73s/it]

epoch  9 loss 124.43 training accuracy 0.77


 22%|██▏       | 11/50 [03:04<10:47, 16.60s/it]

epoch  10 loss 121.43 training accuracy 0.78


 24%|██▍       | 12/50 [03:20<10:29, 16.57s/it]

epoch  11 loss 118.86 training accuracy 0.78


 26%|██▌       | 13/50 [03:37<10:11, 16.54s/it]

epoch  12 loss 116.63 training accuracy 0.79


 28%|██▊       | 14/50 [03:55<10:17, 17.14s/it]

epoch  13 loss 114.68 training accuracy 0.79


 30%|███       | 15/50 [04:13<10:02, 17.23s/it]

epoch  14 loss 112.94 training accuracy 0.80


 32%|███▏      | 16/50 [04:30<09:44, 17.19s/it]

epoch  15 loss 111.39 training accuracy 0.80


 34%|███▍      | 17/50 [04:48<09:35, 17.44s/it]

epoch  16 loss 109.99 training accuracy 0.80


 36%|███▌      | 18/50 [05:04<09:08, 17.14s/it]

epoch  17 loss 108.72 training accuracy 0.81


 38%|███▊      | 19/50 [05:21<08:43, 16.90s/it]

epoch  18 loss 107.58 training accuracy 0.81


 40%|████      | 20/50 [05:37<08:21, 16.73s/it]

epoch  19 loss 106.52 training accuracy 0.81


 42%|████▏     | 21/50 [05:55<08:11, 16.95s/it]

epoch  20 loss 105.56 training accuracy 0.81


 44%|████▍     | 22/50 [06:13<08:03, 17.26s/it]

epoch  21 loss 104.68 training accuracy 0.82


 46%|████▌     | 23/50 [06:30<07:44, 17.19s/it]

epoch  22 loss 103.86 training accuracy 0.82


 48%|████▊     | 24/50 [06:46<07:22, 17.04s/it]

epoch  23 loss 103.11 training accuracy 0.82


 50%|█████     | 25/50 [07:03<06:59, 16.79s/it]

epoch  24 loss 102.41 training accuracy 0.82


 52%|█████▏    | 26/50 [07:19<06:39, 16.64s/it]

epoch  25 loss 101.77 training accuracy 0.82


 54%|█████▍    | 27/50 [07:35<06:21, 16.60s/it]

epoch  26 loss 101.17 training accuracy 0.82


 56%|█████▌    | 28/50 [07:52<06:04, 16.58s/it]

epoch  27 loss 100.61 training accuracy 0.83


 58%|█████▊    | 29/50 [08:09<05:52, 16.79s/it]

epoch  28 loss 100.09 training accuracy 0.83


 60%|██████    | 30/50 [08:27<05:42, 17.13s/it]

epoch  29 loss 99.60 training accuracy 0.83


 62%|██████▏   | 31/50 [08:44<05:21, 16.93s/it]

epoch  30 loss 99.15 training accuracy 0.83


 64%|██████▍   | 32/50 [09:01<05:06, 17.00s/it]

epoch  31 loss 98.72 training accuracy 0.83


 66%|██████▌   | 33/50 [09:17<04:46, 16.83s/it]

epoch  32 loss 98.32 training accuracy 0.83


 68%|██████▊   | 34/50 [09:33<04:26, 16.68s/it]

epoch  33 loss 97.95 training accuracy 0.83


 70%|███████   | 35/50 [09:50<04:09, 16.64s/it]

epoch  34 loss 97.59 training accuracy 0.83


 72%|███████▏  | 36/50 [10:07<03:53, 16.65s/it]

epoch  35 loss 97.26 training accuracy 0.84


 74%|███████▍  | 37/50 [10:25<03:41, 17.07s/it]

epoch  36 loss 96.94 training accuracy 0.84


 76%|███████▌  | 38/50 [10:42<03:25, 17.14s/it]

epoch  37 loss 96.64 training accuracy 0.84


 78%|███████▊  | 39/50 [10:58<03:05, 16.86s/it]

epoch  38 loss 96.36 training accuracy 0.84


 80%|████████  | 40/50 [11:14<02:46, 16.65s/it]

epoch  39 loss 96.09 training accuracy 0.84


 82%|████████▏ | 41/50 [11:31<02:28, 16.53s/it]

epoch  40 loss 95.83 training accuracy 0.84


 84%|████████▍ | 42/50 [11:47<02:11, 16.42s/it]

epoch  41 loss 95.59 training accuracy 0.84


 86%|████████▌ | 43/50 [12:03<01:54, 16.37s/it]

epoch  42 loss 95.36 training accuracy 0.84


 88%|████████▊ | 44/50 [12:20<01:38, 16.43s/it]

epoch  43 loss 95.14 training accuracy 0.84


 90%|█████████ | 45/50 [12:36<01:22, 16.42s/it]

epoch  44 loss 94.93 training accuracy 0.84


 92%|█████████▏| 46/50 [12:54<01:07, 16.99s/it]

epoch  45 loss 94.73 training accuracy 0.84


 94%|█████████▍| 47/50 [13:11<00:51, 17.02s/it]

epoch  46 loss 94.54 training accuracy 0.84


 96%|█████████▌| 48/50 [13:28<00:33, 16.79s/it]

epoch  47 loss 94.36 training accuracy 0.84


 98%|█████████▊| 49/50 [13:44<00:16, 16.64s/it]

epoch  48 loss 94.18 training accuracy 0.85


100%|██████████| 50/50 [14:01<00:00, 16.82s/it]

epoch  49 loss 94.01 training accuracy 0.85


In [54]:
a1, z2, a2, z3, a3, z4, a4 = compute_forward_pass(X_test)
loss = compute_loss(a4, y_test_one_hot)
predictions = predict(a4)
predictions

<ipython-input-31-a5da05856836>:6: RuntimeWarning: overflow encountered in exp
  a2 = 1/(1 + np.exp(-z2))


array([3, 2, 1, ..., 4, 5, 6])

In [55]:
labels = predict(y_test_one_hot)
labels

array([7, 2, 1, ..., 4, 5, 6])

In [56]:
wrong = np.where(predictions != labels, np.matrix([1.]), np.matrix([0.]))
test_accuracy = 1 - (np.sum(wrong) / 10000)
test_accuracy

0.8439

## Conclusion

* For each result, we can see the hyperparameter with learning rate = 0.01, batch_size=50, epoch = 100 has the highest accuracy, the accuracy = 95% and the test accuracy = 100%